name: docker-ci-pipiline
on: push
jobs:
  docker-ci-job:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v6
      - name: image
        run: docker build -t rajkumarck/helloworld-demo-python:rt
      - name: verify image
        run: docker images
      - name: Docker Login
        uses: docker/login-action@v3.6.0
        with:
         username: ${{ vars.DOCKER.USERNAME }}
         password: ${{ secrets.DOCKER_TOKEN }}
      - name: push image
        run: docker push -t rajkumarck/helloworld-demo-python:rt
      - name: container-cleanup
        run: docker-rm -f demo-python-app
    k8scd-job:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v6
      - name: start minikube
        uses: medyagh/setup-minikube@latest    
      - name : Test-minikube
        run: kubectl get pods
      - name : list all pods
        run: kubectl get pods -A
       -name: apply -yaml file
        run: 
          kubectl apply -f k8s/.
          kubectl config set-context --current --namespace=python-app
          kubectl wait --for=condition=ready pod -l app=hello-world
       -name: get-deployment-status
        run: |
          kubectl get ns
          kubectl get deploy, service -n python-app
        -name: test-service-urls
         run: |
          minikube service list
          minikube service my-service --url
          echo -n "------------------opening the service------------------"
          curl $(minikube service my-service --url)/version
        
